# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'goalwidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QSizePolicy, QWidget)

class Ui_profilewidgetDisplay(object):
    def setupUi(self, profilewidgetDisplay):
        if not profilewidgetDisplay.objectName():
            profilewidgetDisplay.setObjectName(u"profilewidgetDisplay")
        profilewidgetDisplay.resize(750, 370)

        self.label = QLabel(profilewidgetDisplay)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(260, 20, 331, 40))
        self.label.setText("Profile")

        self.age = QLabel(profilewidgetDisplay)
        self.age.setObjectName(u"age")
        self.age.setGeometry(QRect(140, 90, 256, 40))

        self.weight = QLabel(profilewidgetDisplay)
        self.weight.setObjectName(u"weight")
        self.weight.setGeometry(QRect(140, 140, 256, 40))

        self.gender = QLabel(profilewidgetDisplay)
        self.gender.setObjectName(u"gender")
        self.gender.setGeometry(QRect(140, 190, 256, 40))

        QMetaObject.connectSlotsByName(profilewidgetDisplay)
    # setupUi

    def retranslateUi(self, profilewidgetDisplay):
        profilewidgetDisplay.setWindowTitle(QCoreApplication.translate("profilewidgetDisplay", u"Form", None))
        self.label.setText(QCoreApplication.translate("profilewidgetDisplay", u"profile", None))
    # retranslateUi
