# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'goalwidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6.QtCore import (QCoreApplication, QMetaObject, QRect)
from PySide6.QtWidgets import (QLabel, QWidget, QLineEdit, QPushButton)

class Ui_profilewidgetDisplay(object):
    def setupUi(self, profilewidgetDisplay):
        if not profilewidgetDisplay.objectName():
            profilewidgetDisplay.setObjectName(u"profilewidgetDisplay")
        profilewidgetDisplay.resize(750, 370)

        self.label = QLabel(profilewidgetDisplay)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(260, 20, 331, 40))
        self.label.setText("Profile")

        self.name = QLineEdit(profilewidgetDisplay)
        self.name.setObjectName(u"name")
        self.name.setGeometry(QRect(140, 50, 256, 30))
        self.name.setReadOnly(True)

        self.age = QLineEdit(profilewidgetDisplay)
        self.age.setObjectName(u"age")
        self.age.setGeometry(QRect(140, 90, 256, 30))
        self.age.setReadOnly(True)

        self.weight = QLineEdit(profilewidgetDisplay)
        self.weight.setObjectName(u"weight")
        self.weight.setGeometry(QRect(140, 140, 256, 30))
        self.weight.setReadOnly(True)

        self.gender = QLineEdit(profilewidgetDisplay)
        self.gender.setObjectName(u"gender")
        self.gender.setGeometry(QRect(140, 190, 256, 30))
        self.gender.setReadOnly(True)

        self.editButton = QPushButton(profilewidgetDisplay)
        self.editButton.setObjectName(u"editButton")
        self.editButton.setGeometry(QRect(140, 240, 100, 30))
        self.editButton.setText("Edit")

        QMetaObject.connectSlotsByName(profilewidgetDisplay)

    def retranslateUi(self, profilewidgetDisplay):
        profilewidgetDisplay.setWindowTitle(QCoreApplication.translate("profilewidgetDisplay", u"Form", None))
        self.label.setText(QCoreApplication.translate("profilewidgetDisplay", u"profile", None))